### ISSUE TITLE
Active usage of repository

### ISSUE THREAD

**Issue by foxish** [kubernetes/application-images#15]
Is this repository in active use? We're no longer using/supporting the images here for spark-native.
Some of the other contents also look stale at this point. If the bits are rotting, we might want to clean them up and repo possibly.

/cc @mattf @spiffxp

**Comment by spiffxp** [comment]
I'm fine calling this repository deprecated and slated to move to [kubernetes-retired](https://github.com/kubernetes-retired) if nobody speaks up for it.  I see there are _no_ collaborators for this repo, which means the only people that can write to it are @kubernetes-incubator/owners

**Comment by mattf** [comment]
+1 retire

**Comment by bgrant0607** [comment]
SGTM

**Comment by spiffxp** [comment]
Done
